In [ ]:
#import libraries
import pandas as pd
import sqlite3

In [2]:
#connect to sqlite 
conn = sqlite3.connect("../database/marketing.db")

print("Database Connected!")

Database Connected!

In [3]:
#loading the clean csv
df = pd.read_csv("../data/cleaned/ad_spend_cleaned.csv")

df.head()

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [4]:
#create the sql table
df.to_sql(
    "marketing_spend",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully!")

DatabaseError: Execution failed on sql '
        SELECT
            name
        FROM
            sqlite_master
        WHERE
            type IN ('table', 'view')
            AND name=?;
        ': file is not a database

In [5]:
df.to_sql(
    "marketing_spend",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully!")

DatabaseError: Execution failed on sql '
        SELECT
            name
        FROM
            sqlite_master
        WHERE
            type IN ('table', 'view')
            AND name=?;
        ': file is not a database

In [6]:
import sqlite3
import pandas as pd

In [7]:
conn = sqlite3.connect("../database/marketing.db")
print("Database Connected!")

Database Connected!

In [8]:
df = pd.read_csv("../data/cleaned/ad_spend_cleaned.csv")

In [9]:
df.to_sql(
    "marketing_spend",
    conn,
    if_exists="replace",
    index=False
)

print("Table Created Successfully!")

DatabaseError: Execution failed on sql '
        SELECT
            name
        FROM
            sqlite_master
        WHERE
            type IN ('table', 'view')
            AND name=?;
        ': file is not a database

In [10]:
import os

print(os.getcwd())
print(os.path.exists("../database"))
print(os.listdir("../database"))

c:\Users\91958\OneDrive\Desktop\aa\Multi-Touch-Marketing-Attribution-ROI-Dashboard\notebook
True
['.ipynb_checkpoints', 'marketing.db']

In [11]:
import os

os.remove("marketing.db")
print("Old database deleted.")

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'marketing.db'

In [12]:
print(os.getcwd())
print(os.listdir("../database"))

c:\Users\91958\OneDrive\Desktop\aa\Multi-Touch-Marketing-Attribution-ROI-Dashboard\notebook
['.ipynb_checkpoints', 'marketing.db']

In [13]:
import os

os.remove("../database/marketing.db")
print("Old database deleted.")

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '../database/marketing.db'

In [14]:
import os

print("Current folder:", os.getcwd())
print("Database folder contents:", os.listdir("../database"))

Current folder: c:\Users\91958\OneDrive\Desktop\aa\Multi-Touch-Marketing-Attribution-ROI-Dashboard\notebook
Database folder contents: ['.ipynb_checkpoints', 'marketing.db']

In [15]:
import os

os.remove("../database/marketing.db")
print("Old database deleted.")

PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: '../database/marketing.db'

In [16]:
import os

db_path = "../database/marketing.db"

print("Exists:", os.path.exists(db_path))
print("Size (bytes):", os.path.getsize(db_path))

Exists: True
Size (bytes): 72

In [17]:
import sqlite3

db_path = "../database/marketing.db"

try:
    conn = sqlite3.connect(db_path)
    conn.execute("SELECT name FROM sqlite_master LIMIT 1;")
    print("✅ Valid SQLite database")
except Exception as e:
    print("❌", e)

❌ file is not a database

In [1]:
import sqlite3

conn = sqlite3.connect("../database/marketing.db")
print("Database created successfully!")

Database created successfully!

In [2]:
df.to_sql(
    "marketing_spend",
    conn,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

NameError: name 'df' is not defined

In [3]:
print(os.path.getsize("../database/marketing.db"))

NameError: name 'os' is not defined

In [4]:
conn.execute("SELECT name FROM sqlite_master LIMIT 1;")

In [5]:
import pandas as pd
import sqlite3
import os

In [6]:
df = pd.read_csv("../data/cleaned/ad_spend_cleaned.csv")

print(df.head())

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [7]:
conn = sqlite3.connect("../database/marketing.db")

print("Database Connected!")

Database Connected!

In [8]:
print("Database exists:", os.path.exists("../database/marketing.db"))
print("Database size:", os.path.getsize("../database/marketing.db"), "bytes")

Database exists: True
Database size: 0 bytes

In [9]:
df.to_sql(
    "marketing_spend",
    conn,
    if_exists="replace",
    index=False
)

print("Table created successfully!")

Table created successfully!

In [10]:
query = """
SELECT *
FROM marketing_spend
LIMIT 5;
"""

pd.read_sql(query, conn)

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [ ]:
#view the table 
query = """
SELECT *
FROM marketing_spend
LIMIT 10;
"""

pd.read_sql(query, conn)

         date         channel            campaign    spend
0  2025-01-01      Google Ads   Competitor Search  2185.43
1  2025-01-01    Facebook Ads         Winter Sale  4778.21
2  2025-01-01      TikTok Ads     Influencer Push  3793.97
3  2025-01-01  Organic Search     Organic Landing     0.00
4  2025-01-02      Google Ads        Brand Search  3193.96
5  2025-01-02    Facebook Ads         Winter Sale  1202.08
6  2025-01-02      TikTok Ads     Influencer Push  1201.98
7  2025-01-02  Organic Search            SEO Blog     0.00
8  2025-01-03      Google Ads   Competitor Search   761.38
9  2025-01-03    Facebook Ads  Lookalike Audience  4397.79

In [12]:
#count the rows
query = """
SELECT COUNT(*) AS total_rows
FROM marketing_spend;
"""

pd.read_sql(query, conn)

   total_rows
0         724

In [13]:
#total marketing spend 
query = """
SELECT
    SUM(spend) AS total_spend
FROM marketing_spend;
"""

pd.read_sql(query, conn)

   total_spend
0   1510660.17

In [14]:
#average spend
query = """
SELECT
    AVG(spend) AS average_spend
FROM marketing_spend;
"""

pd.read_sql(query, conn)

   average_spend
0    2086.547196

In [ ]:
#spend by channel (imp in sql interview questions)
query = """
SELECT
    channel,
    SUM(spend) AS total_spend
FROM marketing_spend
GROUP BY channel
ORDER BY total_spend DESC;
"""

pd.read_sql(query, conn)

          channel  total_spend
0    Facebook Ads    517986.43
1      Google Ads    507942.92
2      TikTok Ads    484730.82
3  Organic Search         0.00

In [16]:
#campaign performance 
query = """
SELECT
    campaign,
    SUM(spend) AS total_spend
FROM marketing_spend
GROUP BY campaign
ORDER BY total_spend DESC;
"""

pd.read_sql(query, conn)

              campaign  total_spend
0          Winter Sale    192858.21
1         Brand Search    185267.47
2         UGC Campaign    172644.43
3          Retargeting    170514.64
4    Competitor Search    164471.28
5      Influencer Push    161883.35
6       Generic Search    158204.17
7   Lookalike Audience    154613.58
8      Awareness Blast    150203.04
9             SEO Blog         0.00
10     Organic Landing         0.00

In [17]:
#highest spend day
query = """
SELECT
    date,
    SUM(spend) AS daily_spend
FROM marketing_spend
GROUP BY date
ORDER BY daily_spend DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

         date  daily_spend
0  2025-03-22     14141.63
1  2025-05-29     13857.22
2  2025-01-12     13753.11
3  2025-06-16     13464.46
4  2025-06-24     13426.63
5  2025-01-18     13242.57
6  2025-06-28     13035.30
7  2025-06-27     12983.04
8  2025-06-19     12741.26
9  2025-04-01     12689.47

In [18]:
#day with zero spend
query = """
SELECT *
FROM marketing_spend
WHERE spend = 0;
"""

pd.read_sql(query, conn)

           date         channel         campaign  spend
0    2025-01-01  Organic Search  Organic Landing    0.0
1    2025-01-02  Organic Search         SEO Blog    0.0
2    2025-01-03  Organic Search         SEO Blog    0.0
3    2025-01-04  Organic Search         SEO Blog    0.0
4    2025-01-05  Organic Search         SEO Blog    0.0
..          ...             ...              ...    ...
176  2025-06-26  Organic Search         SEO Blog    0.0
177  2025-06-27  Organic Search  Organic Landing    0.0
178  2025-06-28  Organic Search         SEO Blog    0.0
179  2025-06-29  Organic Search         SEO Blog    0.0
180  2025-06-30  Organic Search         SEO Blog    0.0

[181 rows x 4 columns]

In [ ]:
##Observation:

#Facebook Ads had the highest spend.
#Google Ads was a close second.
#Organic Search has no ad spend, which is expected because organic traffic doesn't involve direct advertising costs.
#Campaign Performance

#Top campaigns by spend:

#Winter Sale
#Brand Search
#UGC Campaign
#Retargeting
#Competitor Search

##Observation:

#Paid campaigns dominate the spend.
#SEO Blog and Organic Landing show 0 spend, which also makes sense because they belong to the Organic Search channel.

In [ ]:
##windows functions
#Rank campaigns by total spend (This ranks campaigns based on total spend.)
query = """
SELECT
    campaign,
    SUM(spend) AS total_spend,
    RANK() OVER (
        ORDER BY SUM(spend) DESC
    ) AS campaign_rank
FROM marketing_spend
GROUP BY campaign;
"""

pd.read_sql(query, conn)

              campaign  total_spend  campaign_rank
0          Winter Sale    192858.21              1
1         Brand Search    185267.47              2
2         UGC Campaign    172644.43              3
3          Retargeting    170514.64              4
4    Competitor Search    164471.28              5
5      Influencer Push    161883.35              6
6       Generic Search    158204.17              7
7   Lookalike Audience    154613.58              8
8      Awareness Blast    150203.04              9
9             SEO Blog         0.00             10
10     Organic Landing         0.00             10

In [ ]:
#Row number within each channel(This assigns a row number to each record within its channel, ordered by spend.)
query = """
SELECT
    date,
    channel,
    campaign,
    spend,
    ROW_NUMBER() OVER (
        PARTITION BY channel
        ORDER BY spend DESC
    ) AS row_num
FROM marketing_spend;
"""

pd.read_sql(query, conn)

           date       channel            campaign    spend  row_num
0    2025-06-27  Facebook Ads  Lookalike Audience  4984.87        1
1    2025-06-08  Facebook Ads  Lookalike Audience  4968.34        2
2    2025-06-16  Facebook Ads         Retargeting  4937.95        3
3    2025-02-21  Facebook Ads  Lookalike Audience  4935.43        4
4    2025-03-17  Facebook Ads         Retargeting  4878.55        5
..          ...           ...                 ...      ...      ...
719  2025-05-04    TikTok Ads        UGC Campaign   582.00      177
720  2025-04-21    TikTok Ads     Awareness Blast   564.77      178
721  2025-06-06    TikTok Ads     Awareness Blast   554.70      179
722  2025-05-16    TikTok Ads     Influencer Push   548.77      180
723  2025-02-12    TikTok Ads     Awareness Blast   531.28      181

[724 rows x 5 columns]

In [21]:
#Previous day's spend (LAG) (This lets you compare each day's spend to the previous day's spend within the same channel.)
query = """
SELECT
    date,
    channel,
    spend,
    LAG(spend) OVER (
        PARTITION BY channel
        ORDER BY date
    ) AS previous_spend
FROM marketing_spend;
"""

pd.read_sql(query, conn)

           date       channel    spend  previous_spend
0    2025-01-01  Facebook Ads  4778.21             NaN
1    2025-01-02  Facebook Ads  1202.08         4778.21
2    2025-01-03  Facebook Ads  4397.79         1202.08
3    2025-01-04  Facebook Ads   592.63         4397.79
4    2025-01-05  Facebook Ads  1455.53          592.63
..          ...           ...      ...             ...
719  2025-06-26    TikTok Ads  4158.05         1730.33
720  2025-06-27    TikTok Ads  2999.44         4158.05
721  2025-06-28    TikTok Ads  4323.41         2999.44
722  2025-06-29    TikTok Ads  1081.22         4323.41
723  2025-06-30    TikTok Ads  1528.89         1081.22

[724 rows x 4 columns]

In [ ]:
#Next day's spend (LEAD) (This returns the following day's spend for each channel.)
query = """
SELECT
    date,
    channel,
    spend,
    LEAD(spend) OVER (
        PARTITION BY channel
        ORDER BY date
    ) AS next_spend
FROM marketing_spend;
"""

pd.read_sql(query, conn)

           date       channel    spend  next_spend
0    2025-01-01  Facebook Ads  4778.21     1202.08
1    2025-01-02  Facebook Ads  1202.08     4397.79
2    2025-01-03  Facebook Ads  4397.79      592.63
3    2025-01-04  Facebook Ads   592.63     1455.53
4    2025-01-05  Facebook Ads  1455.53     1869.09
..          ...           ...      ...         ...
719  2025-06-26    TikTok Ads  4158.05     2999.44
720  2025-06-27    TikTok Ads  2999.44     4323.41
721  2025-06-28    TikTok Ads  4323.41     1081.22
722  2025-06-29    TikTok Ads  1081.22     1528.89
723  2025-06-30    TikTok Ads  1528.89         NaN

[724 rows x 4 columns]

In [ ]:
##Using ROW_NUMBER(), you can identify the first touch and last touch for each user. 
# LAG() and LEAD() help analyze sequences of interactions, which are key concepts in attribution modeling.

In [23]:
journey_df = pd.read_csv(
    "../data/raw/customer_journey.csv",
    parse_dates=["timestamp"]
)

journey_df.to_sql(
    "customer_journey",
    conn,
    if_exists="replace",
    index=False
)

print("Customer journey table created!")

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/customer_journey.csv'

In [ ]:
#Load it into SQLite custom journy table 
journey_df = pd.read_csv(
    "../data/raw/customer_journey.csv",
    parse_dates=["timestamp"]
)

journey_df.to_sql(
    "customer_journey",
    conn,
    if_exists="replace",
    index=False
)

print("Customer journey table created!")

Customer journey table created!

In [26]:
#First-Click Attribution
WITH_first_touch AS (
    SELECT
        user_id,
        channel,
        campaign,
        conversion,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY timestamp
        ) AS rn
    FROM customer_journey
)
SELECT
    user_id,
    channel,
    campaign
FROM first_touch
WHERE rn = 1;

SyntaxError: invalid syntax (1076054255.py, line 2)

In [27]:
WITH_first_touch AS (
    SELECT
        user_id,
        channel,
        campaign,
        conversion,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY timestamp
        ) AS rn
    FROM customer_journey
)
SELECT
    user_id,
    channel,
    campaign
FROM first_touch
WHERE rn = 1;

SyntaxError: invalid syntax (3825545806.py, line 1)

In [ ]:
#First-Click Attribution (This gives the first marketing touchpoint for every user.)
query = """
WITH first_touch AS (
    SELECT
        user_id,
        channel,
        campaign,
        conversion,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY timestamp
        ) AS rn
    FROM customer_journey
)
SELECT
    user_id,
    channel,
    campaign
FROM first_touch
WHERE rn = 1;
"""

pd.read_sql(query, conn)

   user_id         channel           campaign
0      101    Facebook Ads        Winter Sale
1      102      TikTok Ads       UGC Campaign
2      103      Google Ads  Competitor Search
3      104  Organic Search    Organic Landing
4      105      TikTok Ads    Influencer Push

In [ ]:
#Last-Click Attribution (This gives the last touchpoint before the user's final interaction)
query = """
WITH last_touch AS (
    SELECT
        user_id,
        channel,
        campaign,
        conversion,
        ROW_NUMBER() OVER (
            PARTITION BY user_id
            ORDER BY timestamp DESC
        ) AS rn
    FROM customer_journey
)
SELECT
    user_id,
    channel,
    campaign
FROM last_touch
WHERE rn = 1;
"""

pd.read_sql(query, conn)

   user_id         channel         campaign
0      101  Organic Search         SEO Blog
1      102    Facebook Ads      Retargeting
2      103    Facebook Ads      Winter Sale
3      104  Organic Search  Organic Landing
4      105      Google Ads   Generic Search

In [ ]:
#linear attribution (Each touchpoint receives an equal share of the conversion credit.)
query = """
SELECT
    user_id,
    timestamp,
    channel,
    campaign,
    ROUND(
        1.0 / COUNT(*) OVER (PARTITION BY user_id),
        2
    ) AS attribution_credit
FROM customer_journey
ORDER BY user_id, timestamp;
"""

pd.read_sql(query, conn)

,user_id,timestamp,channel,campaign,attribution_credit
0,101,2025-01-01 09:00:00,Facebook Ads,Winter Sale,0.33
1,101,2025-01-02 10:30:00,Google Ads,Brand Search,0.33
2,101,2025-01-03 14:15:00,Organic Search,SEO Blog,0.33
3,102,2025-01-02 08:45:00,TikTok Ads,UGC Campaign,0.50
4,102,2025-01-03 11:00:00,Facebook Ads,Retargeting,0.50
5,103,2025-01-05 12:00:00,Google Ads,Competitor Search,0.33
6,103,2025-01-06 16:20:00,Google Ads,Brand Search,0.33
7,103,2025-01-07 18:10:00,Facebook Ads,Winter Sale,0.33
8,104,2025-01-08 09:30:00,Organic Search,Organic Landing,1.00
9,105,2025-01-10 10:00:00,TikTok Ads,Influencer Push,0.50
10,105,2025-01-11 15:45:00,Google Ads,Generic Search,0.50

In [ ]:
##What these queries demonstrate
#Use CTEs (WITH ... AS)
#Apply window functions in a realistic business scenario
#Identify the first customer touchpoint
#Identify the last customer touchpoint
#Assign equal credit across all touchpoints (Linear Attribution)