In [1]:
import pandas as pd

df = pd.read_csv("../data/cleaned/ad_spend_cleaned.csv")

df.head()

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [1]:
#Create Sample Business Metrics
import numpy as np

In [2]:
np.random.seed(42)

df["clicks"] = np.random.randint(50, 500, len(df))

df["conversions"] = np.random.randint(5, 50, len(df))

df["revenue"] = np.random.randint(5000, 50000, len(df))

NameError: name 'df' is not defined

In [3]:
np.random.seed(42)

In [4]:
df["clicks"] = np.random.randint(50, 500, len(df))

NameError: name 'df' is not defined

In [5]:
df["conversions"] = np.random.randint(5, 50, len(df))

NameError: name 'df' is not defined

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../data/cleaned/ad_spend_cleaned.csv")

In [8]:
df.head()

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [9]:
np.random.seed(42)

df["clicks"] = np.random.randint(50, 500, len(df))
df["conversions"] = np.random.randint(5, 50, len(df))
df["revenue"] = np.random.randint(5000, 50000, len(df))

In [10]:
df.head()

,date,channel,campaign,spend,clicks,conversions,revenue
0,2025-01-01,Google Ads,Competitor Search,2185.43,152,43,36653
1,2025-01-01,Facebook Ads,Winter Sale,4778.21,485,49,31657
2,2025-01-01,TikTok Ads,Influencer Push,3793.97,398,46,44952
3,2025-01-01,Organic Search,Organic Landing,0.00,320,43,27180
4,2025-01-02,Google Ads,Brand Search,3193.96,156,18,36896

In [11]:
#Calculate KPIs
#CPC (Cost Per Click)
df["CPC"] = df["spend"] / df["clicks"]

In [12]:
#CAC (Customer Acquisition Cost)
df["CAC"] = df["spend"] / df["conversions"]

In [13]:
#ROAS (Return on Ad Spend)
df["ROAS"] = df["revenue"] / df["spend"]

In [14]:
#View Results
df[
    [
        "channel",
        "campaign",
        "spend",
        "clicks",
        "conversions",
        "revenue",
        "CPC",
        "CAC",
        "ROAS",
    ]
].head()

,channel,campaign,spend,clicks,conversions,revenue,CPC,CAC,ROAS
0,Google Ads,Competitor Search,2185.43,152,43,36653,14.377829,50.823953,16.771528
1,Facebook Ads,Winter Sale,4778.21,485,49,31657,9.851979,97.514490,6.625284
2,TikTok Ads,Influencer Push,3793.97,398,46,44952,9.532588,82.477609,11.848275
3,Organic Search,Organic Landing,0.00,320,43,27180,0.000000,0.000000,inf
4,Google Ads,Brand Search,3193.96,156,18,36896,20.474103,177.442222,11.551804

In [15]:
#KPI Summary by Channel
summary = (
    df.groupby("channel")
      .agg({
          "spend": "sum",
          "clicks": "sum",
          "conversions": "sum",
          "revenue": "sum"
      })
)

summary["CPC"] = summary["spend"] / summary["clicks"]
summary["CAC"] = summary["spend"] / summary["conversions"]
summary["ROAS"] = summary["revenue"] / summary["spend"]

summary

,spend,clicks,conversions,revenue,CPC,CAC,ROAS
channel,,,,,,,
Facebook Ads,517986.43,52220,4801,5124078,9.919311,107.891362,9.892302
Google Ads,507942.92,47348,4906,4980052,10.727864,103.535043,9.804354
Organic Search,0.00,49888,4632,4844781,0.000000,0.000000,inf
TikTok Ads,484730.82,51162,4960,5007869,9.474431,97.727988,10.331237