In [40]:
#Importing Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [41]:
#Reading CSV file
adspend=pd.read_csv("/workspaces/Multi-Touch-Marketing-Attribution-ROI-Dashboard/Raw_Data/ad_spend.csv.xls")

In [59]:
adspend.shape

(724, 4)

In [60]:
adspend.columns

Index(['date', 'channel', 'campaign', 'spend'], dtype='str')

In [42]:
print(adspend)

           date         channel            campaign    spend
0    2025-01-01      Google Ads   Competitor Search  2185.43
1    2025-01-01    Facebook Ads         Winter Sale  4778.21
2    2025-01-01      TikTok Ads     Influencer Push  3793.97
3    2025-01-01  Organic Search     Organic Landing     0.00
4    2025-01-02      Google Ads        Brand Search  3193.96
..          ...             ...                 ...      ...
719  2025-06-29  Organic Search            SEO Blog     0.00
720  2025-06-30      Google Ads        Brand Search  4793.23
721  2025-06-30    Facebook Ads  Lookalike Audience  3227.79
722  2025-06-30      TikTok Ads     Awareness Blast  1528.89
723  2025-06-30  Organic Search            SEO Blog     0.00

[724 rows x 4 columns]

In [43]:
adspend.head()

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

In [44]:
adspend.sample(5)

           date         channel            campaign    spend
36   2025-01-10      Google Ads      Generic Search  2814.05
454  2025-04-24      TikTok Ads     Awareness Blast  2630.62
555  2025-05-19  Organic Search     Organic Landing     0.00
363  2025-04-01  Organic Search            SEO Blog     0.00
721  2025-06-30    Facebook Ads  Lookalike Audience  3227.79

In [45]:
#Statistical Analysis
adspend.describe()

             spend
count   724.000000
mean   2086.547196
std    1680.412533
min       0.000000
25%     392.085000
50%    1971.645000
75%    3610.297500
max    4998.730000

In [46]:
adspend.info()

<class 'pandas.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      724 non-null    str
 1   channel   724 non-null    str
 2   campaign  724 non-null    str
 3   spend     724 non-null    float64
dtypes: float64(1), str(3)
memory usage: 22.8 KB

In [47]:
#Converting date column from str datatype to datetime dataype.
adspend['date'] = pd.to_datetime(adspend['date'])

#Normalizing datetime format.Converts time in datetime to zeros.
#Handles data efficiently while working with Power BI.
adspend['date'] = adspend['date'].dt.normalize()

In [48]:
adspend.info()

<class 'pandas.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      724 non-null    datetime64[us]
 1   channel   724 non-null    str
 2   campaign  724 non-null    str
 3   spend     724 non-null    float64
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 22.8 KB

In [56]:
adspend["channel"]=adspend["channel"].str.strip()
adspend["campaign"]=adspend["campaign"].str.strip()

In [50]:
print(adspend.duplicated().sum())

0

In [51]:
print(adspend.isnull().sum())

date        0
channel     0
campaign    0
spend       0
dtype: int64

In [52]:
adspend["channel"].unique()

<StringArray>
['Google Ads', 'Facebook Ads', 'TikTok Ads', 'Organic Search']
Length: 4, dtype: str

In [53]:
adspend["campaign"].unique()

<StringArray>
[ 'Competitor Search',        'Winter Sale',    'Influencer Push',
    'Organic Landing',       'Brand Search',           'SEO Blog',
 'Lookalike Audience',       'UGC Campaign',        'Retargeting',
     'Generic Search',    'Awareness Blast']
Length: 11, dtype: str

In [54]:
adspend["channel"].value_counts()

channel
Google Ads        181
Facebook Ads      181
TikTok Ads        181
Organic Search    181
Name: count, dtype: int64

In [55]:
adspend["campaign"].value_counts()

campaign
SEO Blog              97
Organic Landing       84
Winter Sale           68
Competitor Search     66
Brand Search          63
Retargeting           63
Awareness Blast       61
Influencer Push       60
UGC Campaign          60
Generic Search        52
Lookalike Audience    50
Name: count, dtype: int64

In [63]:
adspend.to_csv("/workspaces/Multi-Touch-Marketing-Attribution-ROI-Dashboard/Cleaned Data/Cleaned_ad_spend.csv")