In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime

import os

In [3]:
print(os.getcwd())

c:\Users\NNEKA AKANNO\Git\Multi-Touch-Marketing-Attribution-ROI-Dashboard\notebooks

In [4]:

print(os.listdir())

['Attribution_model.ipynb', 'cleaning_data.ipynb', 'EDA.ipynb']

In [5]:


print(os.getcwd())

c:\Users\NNEKA AKANNO\Git\Multi-Touch-Marketing-Attribution-ROI-Dashboard\notebooks

In [6]:
print(os.listdir("../data"))

['raw_data']

In [7]:
print(os.path.exists("../data/user_touchpoint.csv"))

False

In [8]:


print(os.listdir("../data/raw_data"))

['adspend.csv', 'conversion.csv', 'customerlogs.csv', 'user_touchpoint.csv']

Loading Dataset

In [9]:
def load_dataset(file_path):
    return pd.read_csv(file_path)

In [10]:
Adspend_Table = load_dataset("../data/raw_data/adspend.csv")
User_Weblogs = load_dataset("../data/raw_data/user_touchpoint.csv")
Customer_Table = load_dataset("../data/raw_data/customerlogs.csv")
Conversions_Table = load_dataset("../data/raw_data/conversion.csv")

Data Inspection

In [11]:
def explore_dataset(df, name):
   
    print("=" * 60)
    print(f"Dataset: {name}")
    print("=" * 60)

    # Shape
    print(f"\nShape: {df.shape[0]} rows × {df.shape[1]} columns")

    # Column names
    print("\nColumns:")
    print(df.columns.tolist())

    # Data types and missing values
    print("\nDataset Information:")
    print(df.info())

    # Missing values
    print("\nMissing Values:")
    print(df.isnull().sum())

    # Summary statistics
    print("\nSummary Statistics:")
    print(df.describe(include='all').T)

    # First five rows
    print("\nFirst Five Rows:")
    display(df.head())

In [12]:
explore_dataset(Adspend_Table, "Ad Spend")
explore_dataset(User_Weblogs, "Web Logs")
explore_dataset(Customer_Table, "CUSTOMER")
explore_dataset(Conversions_Table, "Conversions")

============================================================
Dataset: Ad Spend
============================================================

Shape: 724 rows × 4 columns

Columns:
['date', 'channel', 'campaign', 'spend']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 724 entries, 0 to 723
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      724 non-null    object
 1   channel   724 non-null    object
 2   campaign  724 non-null    object
 3   spend     724 non-null    float64
dtypes: float64(1), object(3)
memory usage: 22.8+ KB
None

Missing Values:
date        0
channel     0
campaign    0
spend       0
dtype: int64

Summary Statistics:
          count unique         top freq         mean          std  min  \
date        724    181  2025-01-01    4          NaN          NaN  NaN
channel     724      4  Google Ads  181          NaN          NaN  NaN
campaign    724     11    SEO Blog   97          NaN          NaN  NaN
spend     724.0    NaN         NaN  NaN  2086.547196  1680.412533  0.0

              25%       50%        75%      max
date          NaN       NaN        NaN      NaN
channel       NaN       NaN        NaN      NaN
campaign      NaN       NaN        NaN      NaN
spend     392.085  1971.645  3610.2975  4998.73

First Five Rows:

         date         channel           campaign    spend
0  2025-01-01      Google Ads  Competitor Search  2185.43
1  2025-01-01    Facebook Ads        Winter Sale  4778.21
2  2025-01-01      TikTok Ads    Influencer Push  3793.97
3  2025-01-01  Organic Search    Organic Landing     0.00
4  2025-01-02      Google Ads       Brand Search  3193.96

============================================================
Dataset: Web Logs
============================================================

Shape: 45815 rows × 10 columns

Columns:
['user_id', 'timestamp', 'region', 'device', 'channel', 'campaign', 'event_type', 'utm_source', 'utm_medium', 'utm_campaign']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45815 entries, 0 to 45814
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   user_id       45815 non-null  object
 1   timestamp     45815 non-null  object
 2   region        45815 non-null  object
 3   device        45815 non-null  object
 4   channel       45815 non-null  object
 5   campaign      45815 non-null  object
 6   event_type    45815 non-null  object
 7   utm_source    43491 non-null  object
 8   utm_medium    43542 non-null  object
 9   utm_campaign  45815 non-null  object
dtypes: object(10)
memory usage: 3.5+ MB
None

Missing Values:
user_id            0
timestamp          0
region             0
device             0
channel            0
campaign           0
event_type         0
utm_source      2324
utm_medium      2273
utm_campaign       0
dtype: int64

Summary Statistics:
              count unique               top   freq
user_id       45815  10000            U07596     10
timestamp     45815  44256  03/26/2025 09:55      4
region        45815      4     North America  11944
device        45815      3           Desktop  15378
channel       45815      4    Organic Search  11482
campaign      45815     11   Organic Landing   5759
event_type    45815      3             Visit  15386
utm_source    43491      4    organic_search  10926
utm_medium    43542      3           organic  14577
utm_campaign  45815     11   Organic Landing   5759

First Five Rows:

,user_id,timestamp,region,device,channel,campaign,event_type,utm_source,utm_medium,utm_campaign
0,U00001,2025-05-14 18:56:35,North America,Desktop,Organic Search,Organic Landing,Visit,organic_search,NaN,Organic Landing
1,U00001,05/16/2025 12:56,North America,Desktop,TikTok Ads,Influencer Push,Product View,tiktok_ads,social,Influencer Push
2,U00002,04/04/2025 15:58,North America,Desktop,TikTok Ads,UGC Campaign,Product View,tiktok_ads,organic,UGC Campaign
3,U00002,2025-04-09 10:58:50,North America,Desktop,Facebook Ads,Retargeting,Visit,facebook_ads,organic,Retargeting
4,U00003,2025-01-23 07:05:32,Asia Pacific,Tablet,Organic Search,Organic Landing,Product View,organic_search,organic,Organic Landing

============================================================
Dataset: CUSTOMER
============================================================

Shape: 10000 rows × 12 columns

Columns:
['customer_key', 'user_id', 'region', 'primary_device', 'first_touch_date', 'last_touch_date', 'total_touchpoints', 'conversion_flag', 'conversion_date', 'customer_lifetime_revenue', 'acquisition_channel', 'acquisition_campaign']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer_key               10000 non-null  int64
 1   user_id                    10000 non-null  object
 2   region                     10000 non-null  object
 3   primary_device             10000 non-null  object
 4   first_touch_date           10000 non-null  object
 5   last_touch_date            10000 non-null  object
 6   total_touchpoints          10000 non-null  int64
 7   conversion_flag            10000 non-null  bool
 8   conversion_date            1564 non-null   object
 9   customer_lifetime_revenue  10000 non-null  float64
 10  acquisition_channel        10000 non-null  object
 11  acquisition_campaign       10000 non-null  object
dtypes: bool(1), float64(1), int64(2), object(8)
memory usage: 869.3+ KB
None

Missing Values:
customer_key                    0
user_id                         0
region                          0
primary_device                  0
first_touch_date                0
last_touch_date                 0
total_touchpoints               0
conversion_flag                 0
conversion_date              8436
customer_lifetime_revenue       0
acquisition_channel             0
acquisition_campaign            0
dtype: int64

Summary Statistics:
                             count unique                  top  freq  \
customer_key               10000.0    NaN                  NaN   NaN
user_id                      10000  10000               U00001     1
region                       10000      4        North America  2596
primary_device               10000      3              Desktop  3397
first_touch_date             10000   9970  2025-05-14 11:52:00     2
last_touch_date              10000   9965  2025-05-12 02:07:00     2
total_touchpoints          10000.0    NaN                  NaN   NaN
conversion_flag              10000      2                False  8436
conversion_date               1564   1564  2025-05-15 09:56:35     1
customer_lifetime_revenue  10000.0    NaN                  NaN   NaN
acquisition_channel          10000      4           TikTok Ads  2536
acquisition_campaign         10000     11             SEO Blog  1273

                                 mean         std  min      25%     50%  \
customer_key                   5000.5  2886.89568  1.0  2500.75  5000.5
user_id                           NaN         NaN  NaN      NaN     NaN
region                            NaN         NaN  NaN      NaN     NaN
primary_device                    NaN         NaN  NaN      NaN     NaN
first_touch_date                  NaN         NaN  NaN      NaN     NaN
last_touch_date                   NaN         NaN  NaN      NaN     NaN
total_touchpoints              4.5815    1.760246  2.0      3.0     5.0
conversion_flag                   NaN         NaN  NaN      NaN     NaN
conversion_date                   NaN         NaN  NaN      NaN     NaN
customer_lifetime_revenue  100.259436  266.870073  0.0      0.0     0.0
acquisition_channel               NaN         NaN  NaN      NaN     NaN
acquisition_campaign              NaN         NaN  NaN      NaN     NaN

                               75%      max
customer_key               7500.25  10000.0
user_id                        NaN      NaN
region                         NaN      NaN
primary_device                 NaN      NaN
first_touch_date               NaN      NaN
last_touch_date                NaN      NaN
total_touchpoints              6.0     10.0
conversion_flag                NaN      NaN
conversion_date                NaN      NaN
customer_lifetime_revenue      0.0  1199.43
acquisition_channel            NaN      NaN
acquisition_campaign           NaN      NaN

First Five Rows:

,customer_key,user_id,region,primary_device,first_touch_date,last_touch_date,total_touchpoints,conversion_flag,conversion_date,customer_lifetime_revenue,acquisition_channel,acquisition_campaign
0,1,U00001,North America,Desktop,2025-05-14 18:56:35,2025-05-16 12:56:00,2,True,2025-05-15 09:56:35,427.99,Organic Search,Organic Landing
1,2,U00002,North America,Desktop,2025-04-04 15:58:00,2025-04-09 10:58:50,2,False,NaN,0.00,TikTok Ads,UGC Campaign
2,3,U00003,Asia Pacific,Tablet,2025-01-23 07:05:32,2025-02-02 02:05:32,4,False,NaN,0.00,Organic Search,Organic Landing
3,4,U00004,Asia Pacific,Mobile,2025-02-10 11:39:23,2025-02-12 19:39:00,2,False,NaN,0.00,Organic Search,SEO Blog
4,5,U00005,Asia Pacific,Tablet,2025-02-21 15:28:06,2025-02-21 22:28:00,2,True,2025-02-24 19:28:00,470.38,Google Ads,Competitor Search

============================================================
Dataset: Conversions
============================================================

Shape: 1564 rows × 3 columns

Columns:
['user_id', 'conversion_date', 'revenue']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1564 entries, 0 to 1563
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   user_id          1564 non-null   object
 1   conversion_date  1564 non-null   object
 2   revenue          1564 non-null   float64
dtypes: float64(1), object(2)
memory usage: 36.8+ KB
None

Missing Values:
user_id            0
conversion_date    0
revenue            0
dtype: int64

Summary Statistics:
                  count unique                  top freq        mean  \
user_id            1564   1564               U00001    1         NaN
conversion_date    1564   1564  2025-05-15 09:56:35    1         NaN
revenue          1564.0    NaN                  NaN  NaN  641.044987

                        std    min      25%     50%       75%      max
user_id                 NaN    NaN      NaN     NaN       NaN      NaN
conversion_date         NaN    NaN      NaN     NaN       NaN      NaN
revenue          329.734181  75.77  363.585  637.22  929.2125  1199.43

First Five Rows:

  user_id      conversion_date  revenue
0  U00001  2025-05-15 09:56:35   427.99
1  U00005  2025-02-24 19:28:00   470.38
2  U00006  2025-04-26 04:32:00   853.58
3  U00008  2025-06-23 04:00:04   790.46
4  U00009  2025-06-13 17:55:21   385.54

Handling Missing UTM Parameters

In [13]:


def missing_and_unique(df, dataset_name):
    """
    Display missing values and unique values for each column.

    Parameters:
        df (DataFrame): Dataset to analyze.
        dataset_name (str): Name of the dataset.
    """

    print("=" * 70)
    print(f"Dataset: {dataset_name}")
    print("=" * 70)

    summary = pd.DataFrame({
        "Data Type": df.dtypes,
        "Missing Values": df.isnull().sum(),
        "Missing (%)": round((df.isnull().sum() / len(df)) * 100, 2),
        "Unique Values": df.nunique()
    })

    display(summary)

    print("\nUnique Values by Column")
    print("-" * 70)

    for col in df.columns:
        print(f"\n{col}:")
        unique_vals = df[col].dropna().unique()

        # Display only if there aren't too many unique values
        if len(unique_vals) <= 20:
            print(unique_vals)
        else:
            print(f"{len(unique_vals)} unique values (too many to display)")

In [14]:
missing_and_unique(Adspend_Table, "Ad Spend")
missing_and_unique(User_Weblogs, "Web Logs")
missing_and_unique(Customer_Table, "CUSTOMER")
missing_and_unique(Conversions_Table, "Conversions")

======================================================================
Dataset: Ad Spend
======================================================================

         Data Type  Missing Values  Missing (%)  Unique Values
date        object               0          0.0            181
channel     object               0          0.0              4
campaign    object               0          0.0             11
spend      float64               0          0.0            544

Unique Values by Column
----------------------------------------------------------------------

date:
181 unique values (too many to display)

channel:
['Google Ads' 'Facebook Ads' 'TikTok Ads' 'Organic Search']

campaign:
['Competitor Search' 'Winter Sale' 'Influencer Push' 'Organic Landing'
 'Brand Search' 'SEO Blog' 'Lookalike Audience' 'UGC Campaign'
 'Retargeting' 'Generic Search' 'Awareness Blast']

spend:
544 unique values (too many to display)
======================================================================
Dataset: Web Logs
======================================================================

             Data Type  Missing Values  Missing (%)  Unique Values
user_id         object               0         0.00          10000
timestamp       object               0         0.00          44256
region          object               0         0.00              4
device          object               0         0.00              3
channel         object               0         0.00              4
campaign        object               0         0.00             11
event_type      object               0         0.00              3
utm_source      object            2324         5.07              4
utm_medium      object            2273         4.96              3
utm_campaign    object               0         0.00             11

Unique Values by Column
----------------------------------------------------------------------

user_id:
10000 unique values (too many to display)

timestamp:
44256 unique values (too many to display)

region:
['North America' 'Asia Pacific' 'Europe' 'South America']

device:
['Desktop' 'Tablet' 'Mobile']

channel:
['Organic Search' 'TikTok Ads' 'Facebook Ads' 'Google Ads']

campaign:
['Organic Landing' 'Influencer Push' 'UGC Campaign' 'Retargeting'
 'Awareness Blast' 'SEO Blog' 'Competitor Search' 'Lookalike Audience'
 'Generic Search' 'Winter Sale' 'Brand Search']

event_type:
['Visit' 'Product View' 'Signup']

utm_source:
['organic_search' 'tiktok_ads' 'facebook_ads' 'google_ads']

utm_medium:
['social' 'organic' 'cpc']

utm_campaign:
['Organic Landing' 'Influencer Push' 'UGC Campaign' 'Retargeting'
 'Awareness Blast' 'SEO Blog' 'Competitor Search' 'Lookalike Audience'
 'Generic Search' 'Winter Sale' 'Brand Search']
======================================================================
Dataset: CUSTOMER
======================================================================

,Data Type,Missing Values,Missing (%),Unique Values
customer_key,int64,0,0.00,10000
user_id,object,0,0.00,10000
region,object,0,0.00,4
primary_device,object,0,0.00,3
first_touch_date,object,0,0.00,9970
last_touch_date,object,0,0.00,9965
total_touchpoints,int64,0,0.00,9
conversion_flag,bool,0,0.00,2
conversion_date,object,8436,84.36,1564
customer_lifetime_revenue,float64,0,0.00,1557
acquisition_channel,object,0,0.00,4
acquisition_campaign,object,0,0.00,11

Unique Values by Column
----------------------------------------------------------------------

customer_key:
10000 unique values (too many to display)

user_id:
10000 unique values (too many to display)

region:
['North America' 'Asia Pacific' 'Europe' 'South America']

primary_device:
['Desktop' 'Tablet' 'Mobile']

first_touch_date:
9970 unique values (too many to display)

last_touch_date:
9965 unique values (too many to display)

total_touchpoints:
[ 2  4  3  6  5  7  8  9 10]

conversion_flag:
[ True False]

conversion_date:
1564 unique values (too many to display)

customer_lifetime_revenue:
1557 unique values (too many to display)

acquisition_channel:
['Organic Search' 'TikTok Ads' 'Google Ads' 'Facebook Ads']

acquisition_campaign:
['Organic Landing' 'UGC Campaign' 'SEO Blog' 'Competitor Search'
 'Awareness Blast' 'Influencer Push' 'Winter Sale' 'Brand Search'
 'Retargeting' 'Generic Search' 'Lookalike Audience']
======================================================================
Dataset: Conversions
======================================================================

                Data Type  Missing Values  Missing (%)  Unique Values
user_id            object               0          0.0           1564
conversion_date    object               0          0.0           1564
revenue           float64               0          0.0           1556

Unique Values by Column
----------------------------------------------------------------------

user_id:
1564 unique values (too many to display)

conversion_date:
1564 unique values (too many to display)

revenue:
1556 unique values (too many to display)

In [15]:
#UTM SOURCE
User_Weblogs.loc[
    (User_Weblogs['channel']=='Facebook Ads') &
    (User_Weblogs['utm_source'].isnull()),
    'utm_source'
] = 'fb_paid'

In [16]:
User_Weblogs.loc[
    (User_Weblogs['channel']=='Google Ads') &
    (User_Weblogs['utm_source'].isnull()),
    'utm_source'
] = 'google_paid'

In [17]:
User_Weblogs.loc[
    (User_Weblogs['channel']=='TikTok Ads') &
    (User_Weblogs['utm_source'].isnull()),
    'utm_source'
] = 'tiktok_paid'

In [18]:
User_Weblogs.loc[
    (User_Weblogs['channel']=='Organic Search') &
    (User_Weblogs['utm_source'].isnull()),
    'utm_source'
] = 'organic_search'

In [19]:
#UTM Medium
missing_pct = (
    User_Weblogs['utm_medium']
    .isnull()
    .mean() * 100
)

print(f"Missing UTM_Medium: {missing_pct:.2f}%")

Missing UTM_Medium: 4.96%

In [20]:
User_Weblogs.groupby('channel')['utm_medium'] \
       .apply(lambda x: x.isnull().sum())

channel
Facebook Ads      574
Google Ads        543
Organic Search    603
TikTok Ads        553
Name: utm_medium, dtype: int64

In [21]:
medium_map = {
    'Facebook Ads': 'paid_social',
    'TikTok Ads': 'paid_social',
    'Google Ads': 'cpc',
    'Organic Search': 'organic'
}

User_Weblogs['utm_medium'] = User_Weblogs['utm_medium'].fillna(
    User_Weblogs['channel'].map(medium_map)
)

In [22]:
medium_standardization = {
    'CPC': 'cpc',
    'Organic': 'organic',
    'Paid Search': 'cpc',
    'Social': 'paid_social',
    'Paid Social': 'paid_social',
}

User_Weblogs['utm_medium'] = (
    User_Weblogs['utm_medium']
    .replace(medium_standardization)
    .str.lower()
)

In [23]:
#Checking for inconsistencies in the conversion_date column
# Customers marked as converted but missing a date
Customer_Table[
    (Customer_Table['conversion_flag'] == True) &
    (Customer_Table['conversion_date'].isna())
]

Empty DataFrame
Columns: [customer_key, user_id, region, primary_device, first_touch_date, last_touch_date, total_touchpoints, conversion_flag, conversion_date, customer_lifetime_revenue, acquisition_channel, acquisition_campaign]
Index: []

In [24]:
# Customers marked as not converted but have a conversion date
Customer_Table[
    (Customer_Table['conversion_flag'] == False) &
    (Customer_Table['conversion_date'].notna())
]

Empty DataFrame
Columns: [customer_key, user_id, region, primary_device, first_touch_date, last_touch_date, total_touchpoints, conversion_flag, conversion_date, customer_lifetime_revenue, acquisition_channel, acquisition_campaign]
Index: []

Standardizing Timestamp format

In [25]:
def convert_to_datetime(df, columns, dayfirst=False):
    """
    Convert one or more columns to datetime format.

    Parameters:
        df (DataFrame): Input DataFrame.
        columns (list): List of column names to convert.
        dayfirst (bool): Set to True if dates are in DD/MM/YYYY format.

    Returns:
        DataFrame: DataFrame with converted datetime columns.
    """

    df = df.copy()

    for col in columns:
        if col in df.columns:
            df[col] = pd.to_datetime(
                df[col],
                errors="coerce",
                dayfirst=dayfirst
            )
            print(f"✓ '{col}' converted to datetime.")
        else:
            print(f"✗ Column '{col}' not found.")

    return df

In [27]:
Conversions_Table = convert_to_datetime(Conversions_Table, ["conversion_date"])

✓ 'conversion_date' converted to datetime.

In [28]:
Adspend_Table = convert_to_datetime(Adspend_Table, ["date"])

✓ 'date' converted to datetime.

In [31]:
User_Weblogs = convert_to_datetime(User_Weblogs, ["timestamp"])

✓ 'timestamp' converted to datetime.

In [30]:
Customer_Table = convert_to_datetime(
    Customer_Table,
    ["first_touch_date", "last_touch_date", "conversion_date"]
)

✓ 'first_touch_date' converted to datetime.
✓ 'last_touch_date' converted to datetime.
✓ 'conversion_date' converted to datetime.

Inspect Datetime

In [32]:
def inspect_datetime(df, columns):
    """
    Inspect datetime columns in a DataFrame.

    Parameters:
        df (DataFrame): Input DataFrame.
        columns (list): List of datetime columns to inspect.
    """

    for col in columns:
        print("=" * 70)
        print(f"Datetime Inspection: {col}")
        print("=" * 70)

        if col not in df.columns:
            print(f"❌ Column '{col}' not found.\n")
            continue

        print(f"Data Type: {df[col].dtype}")
        print(f"Missing (NaT): {df[col].isna().sum()}")
        print(f"Unique Values: {df[col].nunique()}")

        if pd.api.types.is_datetime64_any_dtype(df[col]):
            print(f"Earliest Date: {df[col].min()}")
            print(f"Latest Date: {df[col].max()}")

        print("\nFirst 5 Values:")
        print(df[col].head())

        print("\nLast 5 Values:")
        print(df[col].tail())

        print("\n")

In [33]:
inspect_datetime(Adspend_Table, ["date"])

======================================================================
Datetime Inspection: date
======================================================================
Data Type: datetime64[ns]
Missing (NaT): 0
Unique Values: 181
Earliest Date: 2025-01-01 00:00:00
Latest Date: 2025-06-30 00:00:00

First 5 Values:
0   2025-01-01
1   2025-01-01
2   2025-01-01
3   2025-01-01
4   2025-01-02
Name: date, dtype: datetime64[ns]

Last 5 Values:
719   2025-06-29
720   2025-06-30
721   2025-06-30
722   2025-06-30
723   2025-06-30
Name: date, dtype: datetime64[ns]

In [34]:
inspect_datetime(Customer_Table, ["first_touch_date", "last_touch_date", "conversion_date"])

======================================================================
Datetime Inspection: first_touch_date
======================================================================
Data Type: datetime64[ns]
Missing (NaT): 0
Unique Values: 9970
Earliest Date: 2025-01-01 01:43:10
Latest Date: 2025-06-29 22:57:00

First 5 Values:
0   2025-05-14 18:56:35
1   2025-04-04 15:58:00
2   2025-01-23 07:05:32
3   2025-02-10 11:39:23
4   2025-02-21 15:28:06
Name: first_touch_date, dtype: datetime64[ns]

Last 5 Values:
9995   2025-06-27 08:31:00
9996   2025-01-25 22:33:25
9997   2025-05-04 11:16:00
9998   2025-03-20 23:23:44
9999   2025-02-16 05:32:13
Name: first_touch_date, dtype: datetime64[ns]


======================================================================
Datetime Inspection: last_touch_date
======================================================================
Data Type: datetime64[ns]
Missing (NaT): 0
Unique Values: 9965
Earliest Date: 2025-01-01 14:10:18
Latest Date: 2025-07-22 00:48:14

First 5 Values:
0   2025-05-16 12:56:00
1   2025-04-09 10:58:50
2   2025-02-02 02:05:32
3   2025-02-12 19:39:00
4   2025-02-21 22:28:00
Name: last_touch_date, dtype: datetime64[ns]

Last 5 Values:
9995   2025-07-15 16:31:06
9996   2025-01-28 00:33:25
9997   2025-05-07 17:16:00
9998   2025-03-24 00:23:00
9999   2025-03-04 01:32:00
Name: last_touch_date, dtype: datetime64[ns]


======================================================================
Datetime Inspection: conversion_date
======================================================================
Data Type: datetime64[ns]
Missing (NaT): 8436
Unique Values: 1564
Earliest Date: 2025-01-04 18:05:03
Latest Date: 2025-07-18 08:24:00

First 5 Values:
0   2025-05-15 09:56:35
1                   NaT
2                   NaT
3                   NaT
4   2025-02-24 19:28:00
Name: conversion_date, dtype: datetime64[ns]

Last 5 Values:
9995   2025-07-16 02:31:06
9996                   NaT
9997   2025-05-08 17:16:00
9998   2025-03-23 12:23:44
9999                   NaT
Name: conversion_date, dtype: datetime64[ns]

In [35]:
inspect_datetime(Conversions_Table, ["conversion_date"])

======================================================================
Datetime Inspection: conversion_date
======================================================================
Data Type: datetime64[ns]
Missing (NaT): 0
Unique Values: 1564
Earliest Date: 2025-01-04 18:05:03
Latest Date: 2025-07-18 08:24:00

First 5 Values:
0   2025-05-15 09:56:35
1   2025-02-24 19:28:00
2   2025-04-26 04:32:00
3   2025-06-23 04:00:04
4   2025-06-13 17:55:21
Name: conversion_date, dtype: datetime64[ns]

Last 5 Values:
1559   2025-02-21 01:53:22
1560   2025-03-02 18:29:00
1561   2025-07-16 02:31:06
1562   2025-05-08 17:16:00
1563   2025-03-23 12:23:44
Name: conversion_date, dtype: datetime64[ns]

In [36]:
inspect_datetime(User_Weblogs, ["timestamp"])

======================================================================
Datetime Inspection: timestamp
======================================================================
Data Type: datetime64[ns]
Missing (NaT): 19132
Unique Values: 26132
Earliest Date: 2025-01-01 01:43:10
Latest Date: 2025-07-22 00:48:14

First 5 Values:
0   2025-05-14 18:56:35
1                   NaT
2                   NaT
3   2025-04-09 10:58:50
4   2025-01-23 07:05:32
Name: timestamp, dtype: datetime64[ns]

Last 5 Values:
45810   2025-02-04 06:19:29
45811                   NaT
45812   2025-05-30 20:25:53
45813   2025-05-06 06:38:11
45814                   NaT
Name: timestamp, dtype: datetime64[ns]

Converting to UTC

In [37]:
def convert_to_utc(df, columns):

    df = df.copy()

    for col in columns:
        if col not in df.columns:
            print(f"❌ Column '{col}' not found.")
            continue

        try:
            # Convert to datetime and standardize to UTC
            df[col] = pd.to_datetime(
                df[col],
                errors="coerce",
                utc=True
            )

            print(f"✓ '{col}' converted to UTC.")

        except Exception as e:
            print(f"❌ Error converting '{col}': {e}")

    return df

In [38]:
Adspend_Table = convert_to_utc(Adspend_Table, ["date"])

✓ 'date' converted to UTC.

In [39]:
User_Weblogs = convert_to_utc(User_Weblogs, ["timestamp"])

✓ 'timestamp' converted to UTC.

In [40]:
conversions = convert_to_utc(Conversions_Table, ["conversion_date"])

✓ 'conversion_date' converted to UTC.

In [42]:
Customer_Table = convert_to_utc(
    Customer_Table,
    ["first_touch_date", "last_touch_date", "conversion_date"]
)

✓ 'first_touch_date' converted to UTC.
✓ 'last_touch_date' converted to UTC.
✓ 'conversion_date' converted to UTC.

In [44]:
print(Customer_Table.dtypes)

customer_key                               int64
user_id                                   object
region                                    object
primary_device                            object
first_touch_date             datetime64[ns, UTC]
last_touch_date              datetime64[ns, UTC]
total_touchpoints                          int64
conversion_flag                             bool
conversion_date              datetime64[ns, UTC]
customer_lifetime_revenue                float64
acquisition_channel                       object
acquisition_campaign                      object
dtype: object

In [45]:
print(Adspend_Table.dtypes)

date        datetime64[ns, UTC]
channel                  object
campaign                 object
spend                   float64
dtype: object

In [46]:
print(Conversions_Table.dtypes)

user_id                    object
conversion_date    datetime64[ns]
revenue                   float64
dtype: object

In [47]:
print(User_Weblogs.dtypes)

user_id                      object
timestamp       datetime64[ns, UTC]
region                       object
device                       object
channel                      object
campaign                     object
event_type                   object
utm_source                   object
utm_medium                   object
utm_campaign                 object
dtype: object

In [48]:
def create_date_components(df, columns):

    df = df.copy()

    for col in columns:
        if col not in df.columns:
            print(f"❌ Column '{col}' not found.")
            continue

        if not pd.api.types.is_datetime64_any_dtype(df[col]):
            print(f"❌ '{col}' is not a datetime column.")
            continue

        # Create date components
        df[f"{col}_quarter"] = df[col].dt.quarter
        df[f"{col}_month_name"] = df[col].dt.month_name()
        df[f"{col}_day_name"] = df[col].dt.day_name()
        df[f"{col}_day_of_week"] = df[col].dt.dayofweek
        df[f"{col}_week"] = df[col].dt.isocalendar().week
        df[f"{col}_hour"] = df[col].dt.hour
        df[f"{col}_is_weekend"] = df[col].dt.dayofweek >= 5

        print(f"✓ Date components created for '{col}'.")

    return df

In [49]:
Conversion_Table = create_date_components(Conversions_Table, ["conversion_date"])

✓ Date components created for 'conversion_date'.

In [51]:
Adspend_Table = create_date_components(Adspend_Table, ["date"])

✓ Date components created for 'date'.

In [52]:
User_Weblogs = create_date_components(User_Weblogs, ["timestamp"])

✓ Date components created for 'timestamp'.

In [54]:
Customer_Table = create_date_components(
   Customer_Table,
    ["first_touch_date", "last_touch_date", "conversion_date",]
)

✓ Date components created for 'first_touch_date'.
✓ Date components created for 'last_touch_date'.
✓ Date components created for 'conversion_date'.

In [62]:
User_Weblogs.filter(like="timestamp").head()

                  timestamp
0 2025-05-14 18:56:35+00:00
1                       NaT
2                       NaT
3 2025-04-09 10:58:50+00:00
4 2025-01-23 07:05:32+00:00

In [61]:
User_Weblogs.rename(columns={
    "timestamp_quarter": "quarter",
    "timestamp_month_name": "month_name",
    "timestamp_day_name": "day_name",
    "timestamp_day_of_week": "day_of_week",
    "timestamp_week": "week",
    "timestamp_hour": "hour",
    "timestamp_is_weekend": "is_weekend"
}, inplace=True)

Inspecting Duplicates

In [64]:
def check_duplicates(df, dataset_name, remove=False):

    print("=" * 70)
    print(f"Duplicate Check: {dataset_name}")
    print("=" * 70)

    duplicate_count = df.duplicated().sum()

    print(f"Total Rows: {len(df)}")
    print(f"Duplicate Rows: {duplicate_count}")

    if duplicate_count > 0:
        print("\nDuplicate Records:")
        display(df[df.duplicated()])

        if remove:
            df = df.drop_duplicates().reset_index(drop=True)
            print(f"\n✓ Removed {duplicate_count} duplicate rows.")
            print(f"New Shape: {df.shape}")
    else:
        print("✓ No duplicate rows found.")

    return df

In [65]:
Adspend_Table = check_duplicates(Adspend_Table, "Ad Spend")

======================================================================
Duplicate Check: Ad Spend
======================================================================
Total Rows: 724
Duplicate Rows: 0
✓ No duplicate rows found.

In [66]:
Conversion_Table = check_duplicates(Conversion_Table, "Conversion")

======================================================================
Duplicate Check: Conversion
======================================================================
Total Rows: 1564
Duplicate Rows: 0
✓ No duplicate rows found.

In [67]:
Customer_Table = check_duplicates(Customer_Table, "Customer")

======================================================================
Duplicate Check: Customer
======================================================================
Total Rows: 10000
Duplicate Rows: 0
✓ No duplicate rows found.

In [68]:
User_Weblogs = check_duplicates(User_Weblogs, "User Weblogs")

======================================================================
Duplicate Check: User Weblogs
======================================================================
Total Rows: 45815
Duplicate Rows: 1071

Duplicate Records:

,user_id,timestamp,region,device,channel,campaign,event_type,utm_source,utm_medium,utm_campaign,quarter,month_name,day_name,day_of_week,week,hour,is_weekend
557,U00125,NaT,Asia Pacific,Tablet,TikTok Ads,UGC Campaign,Signup,tiktok_ads,cpc,UGC Campaign,NaN,NaN,NaN,NaN,<NA>,NaN,False
768,U00166,NaT,Europe,Desktop,Organic Search,SEO Blog,Signup,organic_search,cpc,SEO Blog,NaN,NaN,NaN,NaN,<NA>,NaN,False
1313,U00288,NaT,North America,Mobile,Organic Search,SEO Blog,Visit,organic_search,social,SEO Blog,NaN,NaN,NaN,NaN,<NA>,NaN,False
1525,U00338,NaT,Asia Pacific,Desktop,Facebook Ads,Retargeting,Visit,facebook_ads,cpc,Retargeting,NaN,NaN,NaN,NaN,<NA>,NaN,False
1800,U00400,NaT,North America,Tablet,Organic Search,Organic Landing,Signup,organic_search,organic,Organic Landing,NaN,NaN,NaN,NaN,<NA>,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45810,U02465,2025-02-04 06:19:29+00:00,North America,Desktop,TikTok Ads,Awareness Blast,Signup,tiktok_ads,cpc,Awareness Blast,1.0,February,Tuesday,1.0,6,6.0,False
45811,U04713,NaT,North America,Tablet,Facebook Ads,Winter Sale,Product View,facebook_ads,social,Winter Sale,NaN,NaN,NaN,NaN,<NA>,NaN,False
45812,U05414,2025-05-30 20:25:53+00:00,Europe,Mobile,Organic Search,SEO Blog,Signup,organic_search,social,SEO Blog,2.0,May,Friday,4.0,22,20.0,False
45813,U00655,2025-05-06 06:38:11+00:00,Europe,Desktop,Organic Search,SEO Blog,Visit,organic_search,social,SEO Blog,2.0,May,Tuesday,1.0,19,6.0,False
45814,U00530,NaT,North America,Mobile,TikTok Ads,UGC Campaign,Visit,tiktok_ads,cpc,UGC Campaign,NaN,NaN,NaN,NaN,<NA>,NaN,False

In [69]:
def check_duplicates_subset(df, dataset_name, subset):

    duplicates = df[df.duplicated(subset=subset)]

    print("=" * 70)
    print(f"Duplicate Check ({dataset_name})")
    print("=" * 70)
    print(f"Columns Checked: {subset}")
    print(f"Duplicate Rows: {len(duplicates)}")

    if not duplicates.empty:
        display(duplicates)
    else:
        print("✓ No duplicates found.")

In [70]:
check_duplicates_subset(
    User_Weblogs,
    "User Weblogs",
    ["user_id", "timestamp"]
)

======================================================================
Duplicate Check (User Weblogs)
======================================================================
Columns Checked: ['user_id', 'timestamp']
Duplicate Rows: 10939

,user_id,timestamp,region,device,channel,campaign,event_type,utm_source,utm_medium,utm_campaign,quarter,month_name,day_name,day_of_week,week,hour,is_weekend
20,U00007,NaT,Asia Pacific,Desktop,Facebook Ads,Winter Sale,Visit,facebook_ads,organic,Winter Sale,NaN,NaN,NaN,NaN,<NA>,NaN,False
26,U00009,NaT,Asia Pacific,Mobile,Google Ads,Competitor Search,Product View,google_ads,social,Competitor Search,NaN,NaN,NaN,NaN,<NA>,NaN,False
32,U00011,NaT,Asia Pacific,Mobile,Facebook Ads,Lookalike Audience,Product View,facebook_ads,social,Lookalike Audience,NaN,NaN,NaN,NaN,<NA>,NaN,False
37,U00012,NaT,Asia Pacific,Tablet,Google Ads,Brand Search,Visit,google_ads,social,Brand Search,NaN,NaN,NaN,NaN,<NA>,NaN,False
47,U00014,NaT,Asia Pacific,Tablet,Organic Search,Organic Landing,Visit,organic_search,organic,Organic Landing,NaN,NaN,NaN,NaN,<NA>,NaN,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45810,U02465,2025-02-04 06:19:29+00:00,North America,Desktop,TikTok Ads,Awareness Blast,Signup,tiktok_ads,cpc,Awareness Blast,1.0,February,Tuesday,1.0,6,6.0,False
45811,U04713,NaT,North America,Tablet,Facebook Ads,Winter Sale,Product View,facebook_ads,social,Winter Sale,NaN,NaN,NaN,NaN,<NA>,NaN,False
45812,U05414,2025-05-30 20:25:53+00:00,Europe,Mobile,Organic Search,SEO Blog,Signup,organic_search,social,SEO Blog,2.0,May,Friday,4.0,22,20.0,False
45813,U00655,2025-05-06 06:38:11+00:00,Europe,Desktop,Organic Search,SEO Blog,Visit,organic_search,social,SEO Blog,2.0,May,Tuesday,1.0,19,6.0,False
45814,U00530,NaT,North America,Mobile,TikTok Ads,UGC Campaign,Visit,tiktok_ads,cpc,UGC Campaign,NaN,NaN,NaN,NaN,<NA>,NaN,False

User ID Standardization

In [71]:
def standardize_user_id(df, column="user_id"):

    df = df.copy()

    if column not in df.columns:
        print(f"❌ Column '{column}' not found.")
        return df

    # Convert to string
    df[column] = df[column].astype(str)

    # Remove leading/trailing spaces
    df[column] = df[column].str.strip()

    # Remove spaces within IDs
    df[column] = df[column].str.replace(" ", "", regex=False)

    # Convert to uppercase
    df[column] = df[column].str.upper()

    # Remove special characters (keep only letters and numbers)
    df[column] = df[column].str.replace(r"[^A-Z0-9]", "", regex=True)

    # Replace string representations of missing values with NA
    df[column] = df[column].replace(
        ["NAN", "NONE", "NULL", ""],
        pd.NA
    )

    print(f"✓ '{column}' has been standardized.")

    return df

In [73]:
Customer_Table = standardize_user_id(Customer_Table)

User_Weblogs = standardize_user_id(User_Weblogs)

Conversion_Table = standardize_user_id(Conversion_Table)

✓ 'user_id' has been standardized.
✓ 'user_id' has been standardized.
✓ 'user_id' has been standardized.

In [75]:
#Renaming columns for consistency and clarity
Customer_Table= Customer_Table.rename(
    columns={'customer_lifetime_revenue': 'revenue', 
             'acquisition_campaign': 'campaign', 
             'acquisition_channel': 'channel'}
             )

In [74]:
def standardize_channel(df, column="channel"):
    
    df = df.copy()

    if column not in df.columns:
        print(f"❌ Column '{column}' not found.")
        return df

    # Clean text
    df[column] = (
        df[column]
        .astype(str)
        .str.strip()
        .str.lower()
    )

    # Mapping dictionary
    channel_map = {
        # Facebook / Meta
        "facebook": "Facebook",
        "fb": "Facebook",
        "meta": "Facebook",

        # Google Ads
        "google": "Google Ads",
        "google ads": "Google Ads",
        "googleads": "Google Ads",
        "gads": "Google Ads",

        # Email
        "email": "Email",
        "e-mail": "Email",
        "mail": "Email",

        # Organic
        "organic": "Organic",
        "organic search": "Organic",
        "seo": "Organic",

        # Direct
        "direct": "Direct",

        # LinkedIn
        "linkedin": "LinkedIn",
        "linkedin ads": "LinkedIn",

        # Instagram
        "instagram": "Instagram",
        "ig": "Instagram",

        # Twitter/X
        "twitter": "Twitter/X",
        "x": "Twitter/X",

        # YouTube
        "youtube": "YouTube",

        # Display
        "display": "Display",
        "display ads": "Display",

        # Referral
        "referral": "Referral"
    }

    # Apply mapping
    df[column] = df[column].replace(channel_map)

    # Capitalize any values not in the mapping
    df[column] = df[column].str.title()

    print(f"✓ '{column}' has been standardized.")

    return df

In [76]:
Adspend_Table = standardize_channel(Adspend_Table)

User_Weblogs = standardize_channel(User_Weblogs)

Customer_Table = standardize_channel(Customer_Table)

✓ 'channel' has been standardized.
✓ 'channel' has been standardized.
✓ 'channel' has been standardized.

In [77]:
def save_to_csv(df, filename, folder="../data/cleaned_data", index=False):
    
    # Create the folder if it doesn't exist
    os.makedirs(folder, exist_ok=True)

    # Create the full file path
    file_path = os.path.join(folder, filename)

    # Save the DataFrame
    df.to_csv(file_path, index=index)

    print(f"✓ Dataset successfully saved to:\n{file_path}")

In [78]:
save_to_csv(Adspend_Table, "cleaned_Adspend_Table.csv")

save_to_csv(User_Weblogs, "cleaned_User_Weblogs.csv")

save_to_csv(Customer_Table, "cleaned_Customer_Table.csv")

save_to_csv(Conversion_Table, "cleaned_Conversion_Table.csv")

✓ Dataset successfully saved to:
../data/cleaned_data\cleaned_Adspend_Table.csv
✓ Dataset successfully saved to:
../data/cleaned_data\cleaned_User_Weblogs.csv
✓ Dataset successfully saved to:
../data/cleaned_data\cleaned_Customer_Table.csv
✓ Dataset successfully saved to:
../data/cleaned_data\cleaned_Conversion_Table.csv